// Copyright (c) 2025 Gamaliel BENDEGUE. Tous droits réservés.
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'fr' | 'en' | 'nl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations object
const translations = {
  fr: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.shipments': 'Mes envois',
    'nav.map': 'Carte trajets',
    'nav.consolidation': 'Consolidation',
    'nav.customs': 'Assistant douanier',
    'nav.home': 'Accueil',
    'nav.new_shipment': 'Nouvel envoi',
    'nav.support': 'Support',
    'nav.messages': 'Messages',
    'nav.notifications': 'Notifications',
    'nav.profile': 'Mon profil',
    'nav.settings': 'Paramètres du compte',
    'nav.subscription': 'Mon abonnement',
    'nav.help': 'Centre d\'aide',
    'nav.logout': 'Se déconnecter',
    
    // Authentication
    'auth.login': 'Se connecter',
    'auth.register': 'S\'inscrire',
    'auth.email': 'Adresse e-mail',
    'auth.password': 'Mot de passe',
    'auth.confirm_password': 'Confirmer le mot de passe',
    'auth.company': 'Nom de l\'entreprise',
    'auth.first_name': 'Prénom',
    'auth.last_name': 'Nom',
    'auth.phone': 'Téléphone',
    'auth.forgot_password': 'Mot de passe oublié ?',
    'auth.no_account': 'Pas encore de compte ?',
    'auth.already_account': 'Déjà un compte ?',
    'auth.login_title': 'Connexion à hubdispo.be',
    'auth.register_title': 'Créer votre compte hubdispo.be',
    'auth.login_subtitle': 'Accédez à votre plateforme logistique',
    'auth.register_subtitle': 'Rejoignez les PME qui simplifient leurs envois internationaux',
    'auth.terms': 'En créant un compte, vous acceptez nos',
    'auth.terms_link': 'conditions d\'utilisation',
    'auth.privacy_link': 'politique de confidentialité',
    
    // Common
    'common.search_placeholder': 'Rechercher un envoi...',
    'common.search_empty': 'Veuillez saisir un terme de recherche',
    'common.search_launched': 'Recherche lancée pour "{query}"',
    'common.new_notifications': '{count} nouvelles notifications',
    'common.new_messages': '{count} nouveaux messages',
    'common.language': 'Langue',
    
    // Plans
    'plan.business': 'Plan Business',
    'plan.starter': 'Plan Starter',
    'plan.premium': 'Plan Premium',
    
    // Legal
    'legal.terms': 'Conditions d\'utilisation',
    'legal.privacy': 'Politique de confidentialité', 
    'legal.notices': 'Mentions légales',
    'legal.back_to_home': 'Retour à l\'accueil',
    'legal.last_updated': 'Dernière mise �� jour :',
    
    // Support
    'support.help_center': 'Centre d\'aide',
    'support.documentation': 'Documentation',
    'support.guides': 'Guides',
    'support.technical_support': 'Support technique',
    'support.platform_status': 'Statut plateforme',
    'support.back_to_help': 'Retour au centre d\'aide',
    'support.search_placeholder': 'Rechercher dans la documentation...',
    'support.getting_started': 'Démarrage',
    'support.advanced': 'Avancé',
    'support.api_reference': 'Référence API',
    'support.troubleshooting': 'Dépannage',
    'support.step_by_step': 'Guides étape par étape',
    'support.video_tutorials': 'Tutoriels vidéo',
    'support.best_practices': 'Bonnes pratiques',
    'support.contact_support': 'Contacter le support',
    'support.live_chat': 'Chat en direct',
    'support.phone_support': 'Support téléphonique',
    'support.email_support': 'Support email',
    'support.all_systems_operational': 'Tous les systèmes opérationnels',
    'support.operational': 'Opérationnel',
    'support.maintenance': 'Maintenance',
    'support.incident': 'Incident',
    'support.uptime': 'Disponibilité',
    'support.last_24h': 'Dernières 24h',
    'support.last_7d': 'Derniers 7 jours',
    'support.last_30d': 'Derniers 30 jours',
    
    // Homepage
    'home.platform_badge': '🇧🇪 Plateforme 100% belge',
    'home.hero_title_1': 'L\'export international',
    'home.hero_title_2': 'simplifié pour les PME',
    'home.hero_subtitle': 'Micro-consolidation logistique + automatisation douanière intelligente. Envoyez vos petits volumes à l\'international avec la simplicité du national.',
    'home.cta_start_free': 'Démarrer gratuitement',
    'home.cta_see_demo': 'Voir la démo (2 min)',
    'home.cta_dashboard': 'Accéder au dashboard',
    'home.cta_profile': 'Mon profil',
    'home.savings_average': 'Économies moyennes',
    'home.savings_average_value': '40%',
    'home.savings_average_subtitle': 'vs transporteurs traditionnels',
    'home.co2_reduction': 'Réduction CO₂',
    'home.co2_reduction_value': '60%',
    'home.co2_reduction_subtitle': 'grâce à la consolidation',
    'home.time_saved': 'Temps gagné',
    'home.time_saved_value': '80%',
    'home.time_saved_subtitle': 'sur les formalités douanières',
    'home.satisfaction': 'Satisfaction client',
    'home.satisfaction_value': '98%',
    'home.satisfaction_subtitle': 'recommandent hubdispo.be',
    'home.features_title': 'Une plateforme pensée pour les PME belges',
    'home.features_subtitle': 'Fini les complications logistiques. Hubdispo.be transforme l\'export international en processus aussi simple qu\'un envoi national.',
    'home.feature_consolidation': 'Micro-consolidation intelligente',
    'home.feature_consolidation_desc': 'Regroupement automatique de vos petits envois pour optimiser les coûts et réduire l\'impact environnemental.',
    'home.feature_customs': 'Douane automatisée',
    'home.feature_customs_desc': 'Assistant IA qui génère vos déclarations douanières et suit les réglementations en temps réel.',
    'home.feature_tracking': 'Suivi temps réel',
    'home.feature_tracking_desc': 'Visibilité complète sur vos envois, de la collecte à la livraison, avec notifications proactives.',
    'home.feature_pricing': 'Tarification transparente',
    'home.feature_pricing_desc': 'Calculateur en temps réel avec prix tout inclus, sans surprises ni frais cachés.',
    'home.how_it_works_title': 'Comment ça marche ?',
    'home.how_it_works_subtitle': '3 étapes simples pour expédier à l\'international',
    'home.step1_title': 'Déposez votre colis',
    'home.step1_desc': 'Créez votre envoi en ligne, imprimez l\'étiquette et déposez votre colis dans l\'un de nos points relais belges.',
    'home.step2_title': 'Consolidation & Douane',
    'home.step2_desc': 'Notre IA regroupe automatiquement vos envois avec d\'autres et gère toutes les formalités douanières pour vous.',
    'home.step3_title': 'Livraison trackée',
    'home.step3_desc': 'Suivez votre envoi en temps réel jusqu\'à la livraison. Vos clients reçoivent des notifications automatiques.',
    'home.testimonials_title': 'Ils nous font confiance',
    'home.testimonials_subtitle': 'Plus de 500 PME belges utilisent hubdispo.be',
    'home.pricing_title': 'Tarifs transparents, sans surprise',
    'home.pricing_subtitle': 'Choisissez le plan qui correspond à vos besoins d\'export',
    'home.plan_starter': 'Starter',
    'home.plan_business': 'Business',
    'home.plan_enterprise': 'Enterprise',
    'home.plan_starter_desc': 'Parfait pour débuter à l\'international',
    'home.plan_business_desc': 'Idéal pour les PME en croissance',
    'home.plan_enterprise_desc': 'Solution personnalisée pour grandes entreprises',
    'home.plan_popular': 'Populaire',
    'home.plan_custom_price': 'Sur mesure',
    'home.plan_button_start': 'Commencer gratuitement',
    'home.plan_button_trial': 'Essai gratuit 14 jours',
    'home.plan_button_contact': 'Nous contacter',
    'home.cta_final_title': 'Prêt à simplifier vos exports ?',
    'home.cta_final_subtitle': 'Rejoignez les centaines de PME belges qui ont déjà révolutionné leur logistique internationale avec hubdispo.be',
    'home.cta_free_trial': 'Essai gratuit 14 jours',
    'home.cta_talk_expert': 'Parler à un expert',
    'home.feature_setup': 'Configuration en 5 minutes',
    'home.feature_support_fr': 'Support en français',
    'home.feature_instant': 'Activation immédiate',
    
    // Dashboard
    'dashboard.welcome': 'Bonjour, {name} !',
    'dashboard.status_summary': 'Vous avez 2 envois en attente de consolidation et 1 alerte douanière',
    'dashboard.new_shipment': 'Déposer un nouvel envoi',
    'dashboard.view_alerts': 'Voir mes alertes douanières',
    'dashboard.active_shipments': 'Envois actifs',
    'dashboard.consolidation_progress': 'Consolidation en cours',
    'dashboard.monthly_savings': 'Économies ce mois',
    'dashboard.customs_alerts': 'Alertes douanières',
    'dashboard.next_steps': 'Prochaines étapes',
    'dashboard.quick_actions': 'Actions rapides',
    'dashboard.overview': 'Vue d\'ensemble',
    'dashboard.performance': 'Performance',
    'dashboard.goals': 'Objectifs',
    'dashboard.activity': 'Activité',
    'dashboard.recent_activity': 'Activité récente',
    'dashboard.monthly_goals': 'Objectifs mensuels',
    'dashboard.performance_metrics': 'Métriques de performance',
    'dashboard.popular_destinations': 'Destinations populaires',
    'dashboard.action_required': 'Action requise',
    'dashboard.missing_dau': 'DAU manquant pour l\'envoi BE-2024-789 vers l\'Allemagne',
    'dashboard.complete_now': 'Compléter maintenant',
    'dashboard.reports': 'Rapports',
    'dashboard.services': 'Services',
    'dashboard.stats.active_shipments': 'Envois actifs',
    'dashboard.stats.in_consolidation': 'En consolidation',
    'dashboard.stats.in_customs': 'En douane',
    'dashboard.stats.delivered_month': 'Livrés ce mois',
    
    // Shipments
    'shipments.title': 'Mes envois',
    'shipments.subtitle': 'Gérez et suivez tous vos envois internationaux',
    'shipments.search_placeholder': 'Rechercher par numéro, destination...',
    'shipments.filter_all': 'Tous les envois',
    'shipments.filter_active': 'Actifs',
    'shipments.filter_in_transit': 'En transit',
    'shipments.filter_delivered': 'Livrés',
    'shipments.filter_pending': 'En attente',
    'shipments.new_shipment': 'Nouvel envoi',
    'shipments.status.pending': 'En attente',
    'shipments.status.collecting': 'Collecte',
    'shipments.status.in_transit': 'En transit',
    'shipments.status.customs': 'En douane',
    'shipments.status.delivered': 'Livré',
    'shipments.status.consolidation': 'En consolidation',
    'shipments.destination': 'Destination',
    'shipments.departure': 'Départ',
    'shipments.weight': 'Poids',
    'shipments.value': 'Valeur',
    'shipments.created': 'Créé le',
    'shipments.tracking_number': 'N° de suivi',
    'shipments.view_details': 'Voir détails',
    'shipments.track': 'Suivre',
    'shipments.empty': 'Aucun envoi trouvé',
    'shipments.empty_subtitle': 'Commencez par créer votre premier envoi',
    'shipments.total_results': '{count} envoi(s) trouvé(s)',
    
    // Shipment Form
    'shipment_form.title': 'Créer un nouvel envoi',
    'shipment_form.subtitle': 'Remplissez les informations de votre envoi international',
    'shipment_form.sender_info': 'Informations expéditeur',
    'shipment_form.recipient_info': 'Informations destinataire',
    'shipment_form.package_info': 'Informations colis',
    'shipment_form.customs_info': 'Informations douanières',
    'shipment_form.sender_name': 'Nom de l\'expéditeur',
    'shipment_form.sender_company': 'Entreprise expéditrice',
    'shipment_form.sender_address': 'Adresse',
    'shipment_form.sender_city': 'Ville',
    'shipment_form.sender_postal': 'Code postal',
    'shipment_form.sender_country': 'Pays',
    'shipment_form.sender_phone': 'Téléphone',
    'shipment_form.sender_email': 'Email',
    'shipment_form.recipient_name': 'Nom du destinataire',
    'shipment_form.recipient_company': 'Entreprise destinataire',
    'shipment_form.recipient_address': 'Adresse',
    'shipment_form.recipient_city': 'Ville',
    'shipment_form.recipient_postal': 'Code postal',
    'shipment_form.recipient_country': 'Pays',
    'shipment_form.recipient_phone': 'Téléphone',
    'shipment_form.recipient_email': 'Email',
    'shipment_form.package_type': 'Type de colis',
    'shipment_form.package_weight': 'Poids (kg)',
    'shipment_form.package_dimensions': 'Dimensions (L x l x H en cm)',
    'shipment_form.package_value': 'Valeur déclarée (€)',
    'shipment_form.package_description': 'Description du contenu',
    'shipment_form.package_quantity': 'Quantité',
    'shipment_form.customs_purpose': 'Objet de l\'envoi',
    'shipment_form.customs_hs_code': 'Code HS',
    'shipment_form.customs_origin': 'Pays d\'origine',
    'shipment_form.insurance': 'Assurance',
    'shipment_form.insurance_value': 'Valeur assurée (€)',
    'shipment_form.delivery_options': 'Options de livraison',
    'shipment_form.signature_required': 'Signature requise',
    'shipment_form.express_delivery': 'Livraison express',
    'shipment_form.calculate_cost': 'Calculer le coût',
    'shipment_form.estimated_cost': 'Coût estimé',
    'shipment_form.create_shipment': 'Créer l\'envoi',
    'shipment_form.save_draft': 'Sauvegarder le brouillon',
    'shipment_form.required_field': 'Champ obligatoire',
    'shipment_form.success': 'Envoi créé avec succès',
    'shipment_form.error': 'Erreur lors de la création de l\'envoi',
    
    // Tracking
    'tracking.title': 'Suivi de l\'envoi',
    'tracking.subtitle': 'Suivez votre envoi en temps réel',
    'tracking.number': 'Numéro de suivi',
    'tracking.status': 'Statut',
    'tracking.location': 'Localisation',
    'tracking.estimated_delivery': 'Livraison estimée',
    'tracking.timeline': 'Chronologie',
    'tracking.details': 'Détails de l\'envoi',
    'tracking.share': 'Partager le suivi',
    'tracking.download_label': 'Télécharger l\'étiquette',
    'tracking.contact_support': 'Contacter le support',
    'tracking.not_found': 'Envoi non trouvé',
    'tracking.loading': 'Chargement du suivi...',
    'tracking.map_view': 'Vue carte',
    'tracking.list_view': 'Vue liste',
    
    // Customs
    'customs.title': 'Assistant douanier',
    'customs.subtitle': 'Gérez vos déclarations douanières avec l\'IA',
    'customs.generate_dau': 'Générer la DAU',
    'customs.dau_number': 'Numéro DAU',
    'customs.dau_status': 'Statut DAU',
    'customs.customs_value': 'Valeur douanière',
    'customs.duty_tax': 'Droits et taxes',
    'customs.documents': 'Documents',
    'customs.requirements': 'Exigences douanières',
    'customs.country_regulations': 'Réglementations du pays',
    'customs.prohibited_items': 'Articles interdits',
    'customs.restricted_items': 'Articles restreints',
    'customs.ai_suggestions': 'Suggestions de l\'IA',
    'customs.validate_declaration': 'Valider la déclaration',
    'customs.submit_declaration': 'Soumettre la déclaration',
    'customs.declaration_approved': 'Déclaration approuvée',
    'customs.declaration_pending': 'Déclaration en attente',
    'customs.declaration_rejected': 'Déclaration rejetée',
    
    // Consolidation
    'consolidation.title': 'Centre de consolidation',
    'consolidation.subtitle': 'Optimisez vos envois avec la micro-consolidation',
    'consolidation.available_groups': 'Groupes disponibles',
    'consolidation.my_shipments': 'Mes envois en attente',
    'consolidation.join_group': 'Rejoindre le groupe',
    'consolidation.create_group': 'Créer un groupe',
    'consolidation.group_savings': 'Économies du groupe',
    'consolidation.departure_date': 'Date de départ',
    'consolidation.capacity': 'Capacité',
    'consolidation.participants': 'Participants',
    'consolidation.estimated_savings': 'Économies estimées',
    'consolidation.total_weight': 'Poids total',
    'consolidation.total_volume': 'Volume total',
    'consolidation.optimization_score': 'Score d\'optimisation',
    
    // Notifications
    'notifications.title': 'Centre de notifications',
    'notifications.mark_all_read': 'Tout marquer comme lu',
    'notifications.filter_all': 'Toutes',
    'notifications.filter_unread': 'Non lues',
    'notifications.filter_shipments': 'Envois',
    'notifications.filter_customs': 'Douane',
    'notifications.filter_system': 'Système',
    'notifications.empty': 'Aucune notification',
    'notifications.shipment_update': 'Mise à jour d\'envoi',
    'notifications.customs_alert': 'Alerte douanière',
    'notifications.system_update': 'Mise à jour système',
    'notifications.delivery_notification': 'Notification de livraison',
    
    // Reports
    'reports.title': 'Rapports et analyses',
    'reports.subtitle': 'Analysez vos performances logistiques',
    'reports.period': 'Période',
    'reports.last_7_days': '7 derniers jours',
    'reports.last_30_days': '30 derniers jours',
    'reports.last_90_days': '90 derniers jours',
    'reports.this_year': 'Cette année',
    'reports.custom_period': 'Période personnalisée',
    'reports.total_shipments': 'Total des envois',
    'reports.total_savings': 'Économies totales',
    'reports.average_cost': 'Coût moyen',
    'reports.delivery_performance': 'Performance de livraison',
    'reports.popular_destinations': 'Destinations populaires',
    'reports.customs_efficiency': 'Efficacité douanière',
    'reports.export_report': 'Exporter le rapport',
    'reports.generate_report': 'Générer le rapport',
    
    // Settings
    'settings.title': 'Paramètres du compte',
    'settings.profile': 'Profil',
    'settings.company': 'Entreprise',
    'settings.preferences': 'Préférences',
    'settings.notifications': 'Notifications',
    'settings.security': 'Sécurité',
    'settings.billing': 'Facturation',
    'settings.api': 'API',
    'settings.save_changes': 'Sauvegarder les modifications',
    'settings.changes_saved': 'Modifications sauvegardées',
    'settings.language_preference': 'Langue préférée',
    'settings.timezone': 'Fuseau horaire',
    'settings.currency': 'Devise',
    'settings.email_notifications': 'Notifications par email',
    'settings.sms_notifications': 'Notifications par SMS',
    'settings.push_notifications': 'Notifications push',
    
    // Messages
    'messages.title': 'Messages',
    'messages.compose': 'Nouveau message',
    'messages.inbox': 'Boîte de réception',
    'messages.sent': 'Envoyés',
    'messages.drafts': 'Brouillons',
    'messages.archive': 'Archives',
    'messages.subject': 'Sujet',
    'messages.message': 'Message',
    'messages.send': 'Envoyer',
    'messages.reply': 'Répondre',
    'messages.forward': 'Transférer',
    'messages.delete': 'Supprimer',
    'messages.mark_read': 'Marquer comme lu',
    'messages.mark_unread': 'Marquer comme non lu',
    'messages.empty': 'Aucun message',
    
    // Help & Support
    'help.title': 'Centre d\'aide hubdispo.be',
    'help.search_placeholder': 'Rechercher dans l\'aide...',
    'help.popular_topics': 'Sujets populaires',
    'help.getting_started': 'Premiers pas',
    'help.shipping_guide': 'Guide d\'expédition',
    'help.customs_help': 'Aide douanière',
    'help.troubleshooting': 'Dépannage',
    'help.contact_support': 'Contacter le support',
    'help.live_chat': 'Chat en direct',
    'help.phone_support': 'Support téléphonique',
    'help.email_support': 'Support par email',
    'help.video_tutorials': 'Tutoriels vidéo',
    'help.documentation': 'Documentation',
    'help.api_docs': 'Documentation API',
    
    // Subscription
    'subscription.title': 'Mon abonnement',
    'subscription.current_plan': 'Plan actuel',
    'subscription.upgrade': 'Mettre à niveau',
    'subscription.downgrade': 'Rétrograder',
    'subscription.cancel': 'Annuler l\'abonnement',
    'subscription.billing_history': 'Historique de facturation',
    'subscription.next_billing': 'Prochaine facturation',
    'subscription.usage': 'Utilisation',
    'subscription.limits': 'Limites',
    'subscription.features': 'Fonctionnalités',
    'subscription.change_plan': 'Changer de plan',
    
    // Map
    'map.title': 'Carte des trajets',
    'map.shipments_on_map': 'Envois sur la carte',
    'map.filter_by_status': 'Filtrer par statut',
    'map.route_optimization': 'Optimisation des trajets',
    'map.live_tracking': 'Suivi en direct',
    'map.estimated_delivery': 'Livraison estimée',
    'map.view_details': 'Voir les détails',
    'map.consolidation_centers': 'Centres de consolidation',
    
    // FAQ
    'faq.title': 'Questions fréquentes',
    'faq.search_placeholder': 'Rechercher dans la FAQ...',
    'faq.categories': 'Catégories',
    'faq.general': 'Général',
    'faq.shipping': 'Expédition',
    'faq.customs': 'Douane',
    'faq.billing': 'Facturation',
    'faq.technical': 'Technique',
    'faq.helpful': 'Cette réponse vous a-t-elle aidé ?',
    'faq.yes': 'Oui',
    'faq.no': 'Non',
    'faq.contact_support': 'Contacter le support',
    
    // Alerts
    'alerts.title': 'Système d\'alertes intelligent',
    'alerts.custom_alerts': 'Alertes personnalisées',
    'alerts.delivery_alerts': 'Alertes de livraison',
    'alerts.customs_alerts': 'Alertes douanières',
    'alerts.price_alerts': 'Alertes de prix',
    'alerts.create_alert': 'Créer une alerte',
    'alerts.manage_alerts': 'Gérer les alertes',
    'alerts.alert_triggered': 'Alerte déclenchée',
    'alerts.alert_resolved': 'Alerte résolue',
    
    // Status Messages
    'status.loading': 'Chargement...',
    'status.saving': 'Sauvegarde...',
    'status.saved': 'Sauvegardé',
    'status.error': 'Erreur',
    'status.success': 'Succès',
    'status.warning': 'Avertissement',
    'status.info': 'Information',
    'status.connecting': 'Connexion...',
    'status.connected': 'Connecté',
    'status.disconnected': 'Déconnecté',
    
    // Actions
    'actions.save': 'Sauvegarder',
    'actions.cancel': 'Annuler',
    'actions.delete': 'Supprimer',
    'actions.edit': 'Modifier',
    'actions.view': 'Voir',
    'actions.download': 'Télécharger',
    'actions.upload': 'Téléverser',
    'actions.share': 'Partager',
    'actions.copy': 'Copier',
    'actions.print': 'Imprimer',
    'actions.export': 'Exporter',
    'actions.import': 'Importer',
    'actions.search': 'Rechercher',
    'actions.filter': 'Filtrer',
    'actions.sort': 'Trier',
    'actions.refresh': 'Actualiser',
    'actions.close': 'Fermer',
    'actions.back': 'Retour',
    'actions.next': 'Suivant',
    'actions.previous': 'Précédent',
    'actions.continue': 'Continuer',
    'actions.confirm': 'Confirmer',
    'actions.submit': 'Soumettre',
    'actions.send': 'Envoyer',
    'actions.retry': 'Réessayer',
    'actions.undo': 'Annuler',
    'actions.redo': 'Rétablir',
    
    // Footer
    'footer.company': 'Entreprise',
    'footer.about': 'À propos',
    'footer.team': 'Notre équipe',
    'footer.careers': 'Carrières',
    'footer.press': 'Presse',
    'footer.partners': 'Partenaires',
    'footer.product': 'Produit',
    'footer.features': 'Fonctionnalités',
    'footer.pricing': 'Tarifs',
    'footer.api': 'API',
    'footer.integrations': 'Intégrations',
    'footer.updates': 'Mises à jour',
    'footer.contact': 'Contact',
    'footer.address': 'Adresse',
    'footer.phone': 'Téléphone',
    'footer.email': 'Email',
    'footer.hours': 'Horaires',
    'footer.follow_us': 'Suivez-nous',
    'footer.certifications': 'Certifications',
    'footer.iso_desc': 'Sécurité des données',
    'footer.gdpr_desc': 'Conformité européenne',
    'footer.bcorp_desc': 'Impact social positif',
    'footer.copyright': '© {year} hubdispo.be - Tous droits réservés.',
    'footer.made_with_love': 'Conçu avec ❤️ en Belgique',
    'footer.business_hours': 'Lun-Ven: 8h-18h | Sam: 9h-12h',
    'footer.faq': 'Questions fréquentes',
    
    // Video & Demos
    'video.watch_demo': 'Regarder la démo',
    'video.play': 'Lire la vidéo',
    'video.pause': 'Mettre en pause',
    'video.fullscreen': 'Plein écran',
    'video.volume': 'Volume',
    'video.subtitles': 'Sous-titres',
    'video.speed': 'Vitesse',
    'video.quality': 'Qualité',
    'video.loading': 'Chargement de la vidéo...',
    'video.error': 'Erreur lors du chargement de la vidéo',
    'video.duration': 'Durée : {duration}',
    'video.consolidation_demo': 'Démo : Micro-consolidation intelligente',
    'video.customs_demo': 'Démo : Assistant douanier IA',
    'video.tracking_demo': 'Démo : Suivi en temps réel',
    'video.onboarding_intro': 'Introduction à hubdispo.be',
    
    // Maps & Locations
    'map.loading': 'Chargement de la carte...',
    'map.error': 'Erreur lors du chargement de la carte',
    'map.no_locations': 'Aucune localisation trouvée',
    'map.current_location': 'Position actuelle',
    'map.zoom_in': 'Zoomer',
    'map.zoom_out': 'Dézoomer',
    'map.fullscreen': 'Plein écran',
    'map.layers': 'Couches',
    'map.satellite': 'Satellite',
    'map.roadmap': 'Plan',
    'map.hybrid': 'Hybride',
    'map.terrain': 'Relief',
    'map.traffic': 'Trafic',
    'map.shipment_route': 'Trajet de l\'envoi',
    'map.consolidation_center': 'Centre de consolidation',
    'map.pickup_point': 'Point de collecte',
    'map.delivery_point': 'Point de livraison',
    'map.customs_checkpoint': 'Poste douanier',
    'map.estimated_time': 'Temps estimé : {time}',
    'map.distance': 'Distance : {distance} km',
    'map.route_options': 'Options de trajet',
    'map.fastest_route': 'Trajet le plus rapide',
    'map.cheapest_route': 'Trajet le moins cher',
    'map.eco_route': 'Trajet écologique'
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.shipments': 'My shipments',
    'nav.map': 'Route map',
    'nav.consolidation': 'Consolidation',
    'nav.customs': 'Customs assistant',
    'nav.home': 'Home',
    'nav.new_shipment': 'New shipment',
    'nav.support': 'Support',
    'nav.messages': 'Messages',
    'nav.notifications': 'Notifications',
    'nav.profile': 'My profile',
    'nav.settings': 'Account settings',
    'nav.subscription': 'My subscription',
    'nav.help': 'Help center',
    'nav.logout': 'Sign out',
    
    // Authentication
    'auth.login': 'Sign in',
    'auth.register': 'Sign up',
    'auth.email': 'Email address',
    'auth.password': 'Password',
    'auth.confirm_password': 'Confirm password',
    'auth.company': 'Company name',
    'auth.first_name': 'First name',
    'auth.last_name': 'Last name',
    'auth.phone': 'Phone',
    'auth.forgot_password': 'Forgot password?',
    'auth.no_account': 'Don\'t have an account?',
    'auth.already_account': 'Already have an account?',
    'auth.login_title': 'Sign in to hubdispo.be',
    'auth.register_title': 'Create your hubdispo.be account',
    'auth.login_subtitle': 'Access your logistics platform',
    'auth.register_subtitle': 'Join SMEs that simplify their international shipments',
    'auth.terms': 'By creating an account, you agree to our',
    'auth.terms_link': 'terms of use',
    'auth.privacy_link': 'privacy policy',
    
    // Common
    'common.search_placeholder': 'Search a shipment...',
    'common.search_empty': 'Please enter a search term',
    'common.search_launched': 'Search launched for "{query}"',
    'common.new_notifications': '{count} new notifications',
    'common.new_messages': '{count} new messages',
    'common.language': 'Language',
    
    // Plans
    'plan.business': 'Business Plan',
    'plan.starter': 'Starter Plan',
    'plan.premium': 'Premium Plan',
    
    // Legal
    'legal.terms': 'Terms of Use',
    'legal.privacy': 'Privacy Policy', 
    'legal.notices': 'Legal Notices',
    'legal.back_to_home': 'Back to Home',
    'legal.last_updated': 'Last updated:',
    
    // Support
    'support.help_center': 'Help Center',
    'support.documentation': 'Documentation',
    'support.guides': 'Guides',
    'support.technical_support': 'Technical Support',
    'support.platform_status': 'Platform Status',
    'support.back_to_help': 'Back to Help Center',
    'support.search_placeholder': 'Search documentation...',
    'support.getting_started': 'Getting Started',
    'support.advanced': 'Advanced',
    'support.api_reference': 'API Reference',
    'support.troubleshooting': 'Troubleshooting',
    'support.step_by_step': 'Step-by-step guides',
    'support.video_tutorials': 'Video tutorials',
    'support.best_practices': 'Best practices',
    'support.contact_support': 'Contact Support',
    'support.live_chat': 'Live Chat',
    'support.phone_support': 'Phone Support',
    'support.email_support': 'Email Support',
    'support.all_systems_operational': 'All systems operational',
    'support.operational': 'Operational',
    'support.maintenance': 'Maintenance',
    'support.incident': 'Incident',
    'support.uptime': 'Uptime',
    'support.last_24h': 'Last 24h',
    'support.last_7d': 'Last 7 days',
    'support.last_30d': 'Last 30 days',
    
    // Homepage
    'home.platform_badge': '🇧🇪 100% Belgian platform',
    'home.hero_title_1': 'International export',
    'home.hero_title_2': 'simplified for SMEs',
    'home.hero_subtitle': 'Logistics micro-consolidation + intelligent customs automation. Send your small volumes internationally with national-level simplicity.',
    'home.cta_start_free': 'Start for free',
    'home.cta_see_demo': 'Watch demo (2 min)',
    'home.cta_dashboard': 'Access dashboard',
    'home.cta_profile': 'My profile',
    'home.savings_average': 'Average savings',
    'home.savings_average_value': '40%',
    'home.savings_average_subtitle': 'vs traditional carriers',
    'home.co2_reduction': 'CO₂ reduction',
    'home.co2_reduction_value': '60%',
    'home.co2_reduction_subtitle': 'thanks to consolidation',
    'home.time_saved': 'Time saved',
    'home.time_saved_value': '80%',
    'home.time_saved_subtitle': 'on customs formalities',
    'home.satisfaction': 'Customer satisfaction',
    'home.satisfaction_value': '98%',
    'home.satisfaction_subtitle': 'recommend hubdispo.be',
    'home.features_title': 'A platform designed for Belgian SMEs',
    'home.features_subtitle': 'Gone are the logistics complications. Hubdispo.be transforms international export into a process as simple as national shipping.',
    'home.feature_consolidation': 'Intelligent micro-consolidation',
    'home.feature_consolidation_desc': 'Automatic grouping of your small shipments to optimize costs and reduce environmental impact.',
    'home.feature_customs': 'Automated customs',
    'home.feature_customs_desc': 'AI assistant that generates your customs declarations and tracks regulations in real-time.',
    'home.feature_tracking': 'Real-time tracking',
    'home.feature_tracking_desc': 'Complete visibility on your shipments, from pickup to delivery, with proactive notifications.',
    'home.feature_pricing': 'Transparent pricing',
    'home.feature_pricing_desc': 'Real-time calculator with all-inclusive prices, no surprises or hidden fees.',
    'home.how_it_works_title': 'How does it work?',
    'home.how_it_works_subtitle': '3 simple steps to ship internationally',
    'home.step1_title': 'Drop off your package',
    'home.step1_desc': 'Create your shipment online, print the label and drop off your package at one of our Belgian pickup points.',
    'home.step2_title': 'Consolidation & Customs',
    'home.step2_desc': 'Our AI automatically groups your shipments with others and handles all customs formalities for you.',
    'home.step3_title': 'Tracked delivery',
    'home.step3_desc': 'Track your shipment in real-time until delivery. Your customers receive automatic notifications.',
    'home.testimonials_title': 'They trust us',
    'home.testimonials_subtitle': 'More than 500 Belgian SMEs use hubdispo.be',
    'home.pricing_title': 'Transparent pricing, no surprises',
    'home.pricing_subtitle': 'Choose the plan that fits your export needs',
    'home.plan_starter': 'Starter',
    'home.plan_business': 'Business',
    'home.plan_enterprise': 'Enterprise',
    'home.plan_starter_desc': 'Perfect to start internationally',
    'home.plan_business_desc': 'Ideal for growing SMEs',
    'home.plan_enterprise_desc': 'Customized solution for large companies',
    'home.plan_popular': 'Popular',
    'home.plan_custom_price': 'Custom',
    'home.plan_button_start': 'Start for free',
    'home.plan_button_trial': '14-day free trial',
    'home.plan_button_contact': 'Contact us',
    'home.cta_final_title': 'Ready to simplify your exports?',
    'home.cta_final_subtitle': 'Join hundreds of Belgian SMEs that have already revolutionized their international logistics with hubdispo.be',
    'home.cta_free_trial': '14-day free trial',
    'home.cta_talk_expert': 'Talk to an expert',
    'home.feature_setup': '5-minute setup',
    'home.feature_support_fr': 'French support',
    'home.feature_instant': 'Instant activation',
    
    // Dashboard
    'dashboard.welcome': 'Hello, {name}!',
    'dashboard.status_summary': 'You have 2 shipments waiting for consolidation and 1 customs alert',
    'dashboard.new_shipment': 'Create new shipment',
    'dashboard.view_alerts': 'View my customs alerts',
    'dashboard.active_shipments': 'Active shipments',
    'dashboard.consolidation_progress': 'Consolidation in progress',
    'dashboard.monthly_savings': 'This month\'s savings',
    'dashboard.customs_alerts': 'Customs alerts',
    'dashboard.next_steps': 'Next steps',
    'dashboard.quick_actions': 'Quick actions',
    'dashboard.overview': 'Overview',
    'dashboard.performance': 'Performance',
    'dashboard.goals': 'Goals',
    'dashboard.activity': 'Activity',
    'dashboard.recent_activity': 'Recent activity',
    'dashboard.monthly_goals': 'Monthly goals',
    'dashboard.performance_metrics': 'Performance metrics',
    'dashboard.popular_destinations': 'Popular destinations',
    'dashboard.action_required': 'Action required',
    'dashboard.missing_dau': 'Missing DAU for shipment BE-2024-789 to Germany',
    'dashboard.complete_now': 'Complete now',
    'dashboard.reports': 'Reports',
    'dashboard.services': 'Services',
    'dashboard.stats.active_shipments': 'Active shipments',
    'dashboard.stats.in_consolidation': 'In consolidation',
    'dashboard.stats.in_customs': 'In customs',
    'dashboard.stats.delivered_month': 'Delivered this month',
    
    // Shipments
    'shipments.title': 'My Shipments',
    'shipments.subtitle': 'Manage and track all your international shipments',
    'shipments.search_placeholder': 'Search by number, destination...',
    'shipments.filter_all': 'All shipments',
    'shipments.filter_active': 'Active',
    'shipments.filter_in_transit': 'In transit',
    'shipments.filter_delivered': 'Delivered',
    'shipments.filter_pending': 'Pending',
    'shipments.new_shipment': 'New shipment',
    'shipments.status.pending': 'Pending',
    'shipments.status.collecting': 'Collecting',
    'shipments.status.in_transit': 'In transit',
    'shipments.status.customs': 'In customs',
    'shipments.status.delivered': 'Delivered',
    'shipments.status.consolidation': 'In consolidation',
    'shipments.destination': 'Destination',
    'shipments.departure': 'Departure',
    'shipments.weight': 'Weight',
    'shipments.value': 'Value',
    'shipments.created': 'Created on',
    'shipments.tracking_number': 'Tracking number',
    'shipments.view_details': 'View details',
    'shipments.track': 'Track',
    'shipments.empty': 'No shipments found',
    'shipments.empty_subtitle': 'Start by creating your first shipment',
    'shipments.total_results': '{count} shipment(s) found',
    
    // Shipment Form
    'shipment_form.title': 'Create a New Shipment',
    'shipment_form.subtitle': 'Fill in your international shipment information',
    'shipment_form.sender_info': 'Sender Information',
    'shipment_form.recipient_info': 'Recipient Information',
    'shipment_form.package_info': 'Package Information',
    'shipment_form.customs_info': 'Customs Information',
    'shipment_form.sender_name': 'Sender name',
    'shipment_form.sender_company': 'Sender company',
    'shipment_form.sender_address': 'Address',
    'shipment_form.sender_city': 'City',
    'shipment_form.sender_postal': 'Postal code',
    'shipment_form.sender_country': 'Country',
    'shipment_form.sender_phone': 'Phone',
    'shipment_form.sender_email': 'Email',
    'shipment_form.recipient_name': 'Recipient name',
    'shipment_form.recipient_company': 'Recipient company',
    'shipment_form.recipient_address': 'Address',
    'shipment_form.recipient_city': 'City',
    'shipment_form.recipient_postal': 'Postal code',
    'shipment_form.recipient_country': 'Country',
    'shipment_form.recipient_phone': 'Phone',
    'shipment_form.recipient_email': 'Email',
    'shipment_form.package_type': 'Package type',
    'shipment_form.package_weight': 'Weight (kg)',
    'shipment_form.package_dimensions': 'Dimensions (L x W x H in cm)',
    'shipment_form.package_value': 'Declared value (€)',
    'shipment_form.package_description': 'Content description',
    'shipment_form.package_quantity': 'Quantity',
    'shipment_form.customs_purpose': 'Shipment purpose',
    'shipment_form.customs_hs_code': 'HS Code',
    'shipment_form.customs_origin': 'Country of origin',
    'shipment_form.insurance': 'Insurance',
    'shipment_form.insurance_value': 'Insured value (€)',
    'shipment_form.delivery_options': 'Delivery options',
    'shipment_form.signature_required': 'Signature required',
    'shipment_form.express_delivery': 'Express delivery',
    'shipment_form.calculate_cost': 'Calculate cost',
    'shipment_form.estimated_cost': 'Estimated cost',
    'shipment_form.create_shipment': 'Create shipment',
    'shipment_form.save_draft': 'Save draft',
    'shipment_form.required_field': 'Required field',
    'shipment_form.success': 'Shipment created successfully',
    'shipment_form.error': 'Error creating shipment',
    
    // Tracking
    'tracking.title': 'Shipment Tracking',
    'tracking.subtitle': 'Track your shipment in real-time',
    'tracking.number': 'Tracking number',
    'tracking.status': 'Status',
    'tracking.location': 'Location',
    'tracking.estimated_delivery': 'Estimated delivery',
    'tracking.timeline': 'Timeline',
    'tracking.details': 'Shipment details',
    'tracking.share': 'Share tracking',
    'tracking.download_label': 'Download label',
    'tracking.contact_support': 'Contact support',
    'tracking.not_found': 'Shipment not found',
    'tracking.loading': 'Loading tracking...',
    'tracking.map_view': 'Map view',
    'tracking.list_view': 'List view',
    
    // Customs
    'customs.title': 'Customs Assistant',
    'customs.subtitle': 'Manage your customs declarations with AI',
    'customs.generate_dau': 'Generate DAU',
    'customs.dau_number': 'DAU number',
    'customs.dau_status': 'DAU status',
    'customs.customs_value': 'Customs value',
    'customs.duty_tax': 'Duties and taxes',
    'customs.documents': 'Documents',
    'customs.requirements': 'Customs requirements',
    'customs.country_regulations': 'Country regulations',
    'customs.prohibited_items': 'Prohibited items',
    'customs.restricted_items': 'Restricted items',
    'customs.ai_suggestions': 'AI suggestions',
    'customs.validate_declaration': 'Validate declaration',
    'customs.submit_declaration': 'Submit declaration',
    'customs.declaration_approved': 'Declaration approved',
    'customs.declaration_pending': 'Declaration pending',
    'customs.declaration_rejected': 'Declaration rejected',
    
    // Consolidation
    'consolidation.title': 'Consolidation Center',
    'consolidation.subtitle': 'Optimize your shipments with micro-consolidation',
    'consolidation.available_groups': 'Available groups',
    'consolidation.my_shipments': 'My pending shipments',
    'consolidation.join_group': 'Join group',
    'consolidation.create_group': 'Create group',
    'consolidation.group_savings': 'Group savings',
    'consolidation.departure_date': 'Departure date',
    'consolidation.capacity': 'Capacity',
    'consolidation.participants': 'Participants',
    'consolidation.estimated_savings': 'Estimated savings',
    'consolidation.total_weight': 'Total weight',
    'consolidation.total_volume': 'Total volume',
    'consolidation.optimization_score': 'Optimization score',
    
    // Notifications
    'notifications.title': 'Notification Center',
    'notifications.mark_all_read': 'Mark all as read',
    'notifications.filter_all': 'All',
    'notifications.filter_unread': 'Unread',
    'notifications.filter_shipments': 'Shipments',
    'notifications.filter_customs': 'Customs',
    'notifications.filter_system': 'System',
    'notifications.empty': 'No notifications',
    'notifications.shipment_update': 'Shipment update',
    'notifications.customs_alert': 'Customs alert',
    'notifications.system_update': 'System update',
    'notifications.delivery_notification': 'Delivery notification',
    
    // Reports
    'reports.title': 'Reports and Analytics',
    'reports.subtitle': 'Analyze your logistics performance',
    'reports.period': 'Period',
    'reports.last_7_days': 'Last 7 days',
    'reports.last_30_days': 'Last 30 days',
    'reports.last_90_days': 'Last 90 days',
    'reports.this_year': 'This year',
    'reports.custom_period': 'Custom period',
    'reports.total_shipments': 'Total shipments',
    'reports.total_savings': 'Total savings',
    'reports.average_cost': 'Average cost',
    'reports.delivery_performance': 'Delivery performance',
    'reports.popular_destinations': 'Popular destinations',
    'reports.customs_efficiency': 'Customs efficiency',
    'reports.export_report': 'Export report',
    'reports.generate_report': 'Generate report',
    
    // Settings
    'settings.title': 'Account Settings',
    'settings.profile': 'Profile',
    'settings.company': 'Company',
    'settings.preferences': 'Preferences',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    'settings.billing': 'Billing',
    'settings.api': 'API',
    'settings.save_changes': 'Save changes',
    'settings.changes_saved': 'Changes saved',
    'settings.language_preference': 'Language preference',
    'settings.timezone': 'Timezone',
    'settings.currency': 'Currency',
    'settings.email_notifications': 'Email notifications',
    'settings.sms_notifications': 'SMS notifications',
    'settings.push_notifications': 'Push notifications',
    
    // Messages
    'messages.title': 'Messages',
    'messages.compose': 'New message',
    'messages.inbox': 'Inbox',
    'messages.sent': 'Sent',
    'messages.drafts': 'Drafts',
    'messages.archive': 'Archive',
    'messages.subject': 'Subject',
    'messages.message': 'Message',
    'messages.send': 'Send',
    'messages.reply': 'Reply',
    'messages.forward': 'Forward',
    'messages.delete': 'Delete',
    'messages.mark_read': 'Mark as read',
    'messages.mark_unread': 'Mark as unread',
    'messages.empty': 'No messages',
    
    // Help & Support
    'help.title': 'hubdispo.be Help Center',
    'help.search_placeholder': 'Search help...',
    'help.popular_topics': 'Popular topics',
    'help.getting_started': 'Getting started',
    'help.shipping_guide': 'Shipping guide',
    'help.customs_help': 'Customs help',
    'help.troubleshooting': 'Troubleshooting',
    'help.contact_support': 'Contact support',
    'help.live_chat': 'Live chat',
    'help.phone_support': 'Phone support',
    'help.email_support': 'Email support',
    'help.video_tutorials': 'Video tutorials',
    'help.documentation': 'Documentation',
    'help.api_docs': 'API documentation',
    
    // Subscription
    'subscription.title': 'My Subscription',
    'subscription.current_plan': 'Current plan',
    'subscription.upgrade': 'Upgrade',
    'subscription.downgrade': 'Downgrade',
    'subscription.cancel': 'Cancel subscription',
    'subscription.billing_history': 'Billing history',
    'subscription.next_billing': 'Next billing',
    'subscription.usage': 'Usage',
    'subscription.limits': 'Limits',
    'subscription.features': 'Features',
    'subscription.change_plan': 'Change plan',
    
    // Map
    'map.title': 'Route Map',
    'map.shipments_on_map': 'Shipments on map',
    'map.filter_by_status': 'Filter by status',
    'map.route_optimization': 'Route optimization',
    'map.live_tracking': 'Live tracking',
    'map.estimated_delivery': 'Estimated delivery',
    'map.view_details': 'View details',
    'map.consolidation_centers': 'Consolidation centers',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.search_placeholder': 'Search FAQ...',
    'faq.categories': 'Categories',
    'faq.general': 'General',
    'faq.shipping': 'Shipping',
    'faq.customs': 'Customs',
    'faq.billing': 'Billing',
    'faq.technical': 'Technical',
    'faq.helpful': 'Was this answer helpful?',
    'faq.yes': 'Yes',
    'faq.no': 'No',
    'faq.contact_support': 'Contact support',
    
    // Alerts
    'alerts.title': 'Intelligent Alert System',
    'alerts.custom_alerts': 'Custom alerts',
    'alerts.delivery_alerts': 'Delivery alerts',
    'alerts.customs_alerts': 'Customs alerts',
    'alerts.price_alerts': 'Price alerts',
    'alerts.create_alert': 'Create alert',
    'alerts.manage_alerts': 'Manage alerts',
    'alerts.alert_triggered': 'Alert triggered',
    'alerts.alert_resolved': 'Alert resolved',
    
    // Status Messages
    'status.loading': 'Loading...',
    'status.saving': 'Saving...',
    'status.saved': 'Saved',
    'status.error': 'Error',
    'status.success': 'Success',
    'status.warning': 'Warning',
    'status.info': 'Information',
    'status.connecting': 'Connecting...',
    'status.connected': 'Connected',
    'status.disconnected': 'Disconnected',
    
    // Actions
    'actions.save': 'Save',
    'actions.cancel': 'Cancel',
    'actions.delete': 'Delete',
    'actions.edit': 'Edit',
    'actions.view': 'View',
    'actions.download': 'Download',
    'actions.upload': 'Upload',
    'actions.share': 'Share',
    'actions.copy': 'Copy',
    'actions.print': 'Print',
    'actions.export': 'Export',
    'actions.import': 'Import',
    'actions.search': 'Search',
    'actions.filter': 'Filter',
    'actions.sort': 'Sort',
    'actions.refresh': 'Refresh',
    'actions.close': 'Close',
    'actions.back': 'Back',
    'actions.next': 'Next',
    'actions.previous': 'Previous',
    'actions.continue': 'Continue',
    'actions.confirm': 'Confirm',
    'actions.submit': 'Submit',
    'actions.send': 'Send',
    'actions.retry': 'Retry',
    'actions.undo': 'Undo',
    'actions.redo': 'Redo'
  },
  nl: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.shipments': 'Mijn zendingen',
    'nav.map': 'Routekaart',
    'nav.consolidation': 'Consolidatie',
    'nav.customs': 'Douane assistent',
    'nav.home': 'Home',
    'nav.new_shipment': 'Nieuwe zending',
    'nav.support': 'Ondersteuning',
    'nav.messages': 'Berichten',
    'nav.notifications': 'Meldingen',
    'nav.profile': 'Mijn profiel',
    'nav.settings': 'Account instellingen',
    'nav.subscription': 'Mijn abonnement',
    'nav.help': 'Helpcentrum',
    'nav.logout': 'Uitloggen',
    
    // Authentication
    'auth.login': 'Inloggen',
    'auth.register': 'Registreren',
    'auth.email': 'E-mailadres',
    'auth.password': 'Wachtwoord',
    'auth.confirm_password': 'Bevestig wachtwoord',
    'auth.company': 'Bedrijfsnaam',
    'auth.first_name': 'Voornaam',
    'auth.last_name': 'Achternaam',
    'auth.phone': 'Telefoon',
    'auth.forgot_password': 'Wachtwoord vergeten?',
    'auth.no_account': 'Nog geen account?',
    'auth.already_account': 'Al een account?',
    'auth.login_title': 'Inloggen op hubdispo.be',
    'auth.register_title': 'Maak je hubdispo.be account aan',
    'auth.login_subtitle': 'Toegang tot je logistiek platform',
    'auth.register_subtitle': 'Sluit je aan bij KMO\'s die hun internationale zendingen vereenvoudigen',
    'auth.terms': 'Door een account aan te maken, ga je akkoord met onze',
    'auth.terms_link': 'gebruiksvoorwaarden',
    'auth.privacy_link': 'privacybeleid',
    
    // Common
    'common.search_placeholder': 'Zoek een zending...',
    'common.search_empty': 'Voer een zoekterm in',
    'common.search_launched': 'Zoekopdracht gestart voor "{query}"',
    'common.new_notifications': '{count} nieuwe meldingen',
    'common.new_messages': '{count} nieuwe berichten',
    'common.language': 'Taal',
    
    // Plans
    'plan.business': 'Business Plan',
    'plan.starter': 'Starter Plan',
    'plan.premium': 'Premium Plan',
    
    // Legal
    'legal.terms': 'Gebruiksvoorwaarden',
    'legal.privacy': 'Privacybeleid', 
    'legal.notices': 'Juridische vermeldingen',
    'legal.back_to_home': 'Terug naar Home',
    'legal.last_updated': 'Laatst bijgewerkt:',
    
    // Support
    'support.help_center': 'Helpcentrum',
    'support.documentation': 'Documentatie',
    'support.guides': 'Gidsen',
    'support.technical_support': 'Technische ondersteuning',
    'support.platform_status': 'Platform status',
    'support.back_to_help': 'Terug naar helpcentrum',
    'support.search_placeholder': 'Zoek in documentatie...',
    'support.getting_started': 'Aan de slag',
    'support.advanced': 'Geavanceerd',
    'support.api_reference': 'API Referentie',
    'support.troubleshooting': 'Probleemoplossing',
    'support.step_by_step': 'Stap-voor-stap gidsen',
    'support.video_tutorials': 'Video tutorials',
    'support.best_practices': 'Beste praktijken',
    'support.contact_support': 'Contact ondersteuning',
    'support.live_chat': 'Live chat',
    'support.phone_support': 'Telefoonondersteuning',
    'support.email_support': 'E-mailondersteuning',
    'support.all_systems_operational': 'Alle systemen operationeel',
    'support.operational': 'Operationeel',
    'support.maintenance': 'Onderhoud',
    'support.incident': 'Incident',
    'support.uptime': 'Uptime',
    'support.last_24h': 'Laatste 24u',
    'support.last_7d': 'Laatste 7 dagen',
    'support.last_30d': 'Laatste 30 dagen',
    
    // Homepage
    'home.platform_badge': '🇧🇪 100% Belgisch platform',
    'home.hero_title_1': 'Internationale export',
    'home.hero_title_2': 'vereenvoudigd voor KMO\'s',
    'home.hero_subtitle': 'Logistieke micro-consolidatie + intelligente douane-automatisering. Verzend je kleine volumes internationaal met de eenvoud van nationaal.',
    'home.cta_start_free': 'Gratis beginnen',
    'home.cta_see_demo': 'Demo bekijken (2 min)',
    'home.cta_dashboard': 'Naar dashboard',
    'home.cta_profile': 'Mijn profiel',
    'home.savings_average': 'Gemiddelde besparingen',
    'home.savings_average_value': '40%',
    'home.savings_average_subtitle': 'vs traditionele vervoerders',
    'home.co2_reduction': 'CO₂ reductie',
    'home.co2_reduction_value': '60%',
    'home.co2_reduction_subtitle': 'dankzij consolidatie',
    'home.time_saved': 'Tijd bespaard',
    'home.time_saved_value': '80%',
    'home.time_saved_subtitle': 'op douaneformaliteiten',
    'home.satisfaction': 'Klanttevredenheid',
    'home.satisfaction_value': '98%',
    'home.satisfaction_subtitle': 'beveelt hubdispo.be aan',
    'home.features_title': 'Een platform ontworpen voor Belgische KMO\'s',
    'home.features_subtitle': 'Voorbij zijn de logistieke complicaties. Hubdispo.be transformeert internationale export in een proces zo eenvoudig als nationale verzending.',
    'home.feature_consolidation': 'Intelligente micro-consolidatie',
    'home.feature_consolidation_desc': 'Automatische groepering van je kleine zendingen om kosten te optimaliseren en milieu-impact te verminderen.',
    'home.feature_customs': 'Geautomatiseerde douane',
    'home.feature_customs_desc': 'AI-assistent die je douaneaangiftes genereert en regelgeving in real-time volgt.',
    'home.feature_tracking': 'Real-time tracking',
    'home.feature_tracking_desc': 'Volledige zichtbaarheid op je zendingen, van ophaling tot levering, met proactieve meldingen.',
    'home.feature_pricing': 'Transparante prijsstelling',
    'home.feature_pricing_desc': 'Real-time calculator met all-inclusive prijzen, geen verrassingen of verborgen kosten.',
    'home.how_it_works_title': 'Hoe werkt het?',
    'home.how_it_works_subtitle': '3 eenvoudige stappen om internationaal te verzenden',
    'home.step1_title': 'Breng je pakket',
    'home.step1_desc': 'Maak je zending online aan, print het label en breng je pakket naar een van onze Belgische afhaalpunten.',
    'home.step2_title': 'Consolidatie & Douane',
    'home.step2_desc': 'Onze AI groepeert automatisch je zendingen met andere en regelt alle douaneformaliteiten voor je.',
    'home.step3_title': 'Getrackte levering',
    'home.step3_desc': 'Volg je zending in real-time tot levering. Je klanten ontvangen automatische meldingen.',
    'home.testimonials_title': 'Zij vertrouwen ons',
    'home.testimonials_subtitle': 'Meer dan 500 Belgische KMO\'s gebruiken hubdispo.be',
    'home.pricing_title': 'Transparante prijzen, geen verrassingen',
    'home.pricing_subtitle': 'Kies het plan dat past bij je exportbehoeften',
    'home.plan_starter': 'Starter',
    'home.plan_business': 'Business',
    'home.plan_enterprise': 'Enterprise',
    'home.plan_starter_desc': 'Perfect om internationaal te beginnen',
    'home.plan_business_desc': 'Ideaal voor groeiende KMO\'s',
    'home.plan_enterprise_desc': 'Op maat gemaakte oplossing voor grote bedrijven',
    'home.plan_popular': 'Populair',
    'home.plan_custom_price': 'Op maat',
    'home.plan_button_start': 'Gratis beginnen',
    'home.plan_button_trial': '14 dagen gratis proef',
    'home.plan_button_contact': 'Contacteer ons',
    'home.cta_final_title': 'Klaar om je export te vereenvoudigen?',
    'home.cta_final_subtitle': 'Sluit je aan bij honderden Belgische KMO\'s die hun internationale logistiek al hebben gerevolutioneerd met hubdispo.be',
    'home.cta_free_trial': '14 dagen gratis proef',
    'home.cta_talk_expert': 'Praat met een expert',
    'home.feature_setup': '5 minuten setup',
    'home.feature_support_fr': 'Franse ondersteuning',
    'home.feature_instant': 'Directe activering',
    
    // Dashboard
    'dashboard.welcome': 'Hallo, {name}!',
    'dashboard.status_summary': 'Je hebt 2 zendingen die wachten op consolidatie en 1 douane-alert',
    'dashboard.new_shipment': 'Nieuwe zending aanmaken',
    'dashboard.view_alerts': 'Mijn douane-alerts bekijken',
    'dashboard.active_shipments': 'Actieve zendingen',
    'dashboard.consolidation_progress': 'Consolidatie in uitvoering',
    'dashboard.monthly_savings': 'Besparingen deze maand',
    'dashboard.customs_alerts': 'Douane alerts',
    'dashboard.next_steps': 'Volgende stappen',
    'dashboard.quick_actions': 'Snelle acties',
    'dashboard.overview': 'Overzicht',
    'dashboard.performance': 'Prestaties',
    'dashboard.goals': 'Doelstellingen',
    'dashboard.activity': 'Activiteit',
    'dashboard.recent_activity': 'Recente activiteit',
    'dashboard.monthly_goals': 'Maandelijkse doelstellingen',
    'dashboard.performance_metrics': 'Prestatie statistieken',
    'dashboard.popular_destinations': 'Populaire bestemmingen',
    'dashboard.action_required': 'Actie vereist',
    'dashboard.missing_dau': 'Ontbrekende DAU voor zending BE-2024-789 naar Duitsland',
    'dashboard.complete_now': 'Nu voltooien',
    'dashboard.reports': 'Rapporten',
    'dashboard.services': 'Services',
    'dashboard.stats.active_shipments': 'Actieve zendingen',
    'dashboard.stats.in_consolidation': 'In consolidatie',
    'dashboard.stats.in_customs': 'In douane',
    'dashboard.stats.delivered_month': 'Geleverd deze maand',
    
    // Shipments
    'shipments.title': 'Mijn Zendingen',
    'shipments.subtitle': 'Beheer en volg al je internationale zendingen',
    'shipments.search_placeholder': 'Zoek op nummer, bestemming...',
    'shipments.filter_all': 'Alle zendingen',
    'shipments.filter_active': 'Actief',
    'shipments.filter_in_transit': 'Onderweg',
    'shipments.filter_delivered': 'Geleverd',
    'shipments.filter_pending': 'In afwachting',
    'shipments.new_shipment': 'Nieuwe zending',
    'shipments.status.pending': 'In afwachting',
    'shipments.status.collecting': 'Ophaling',
    'shipments.status.in_transit': 'Onderweg',
    'shipments.status.customs': 'In douane',
    'shipments.status.delivered': 'Geleverd',
    'shipments.status.consolidation': 'In consolidatie',
    'shipments.destination': 'Bestemming',
    'shipments.departure': 'Vertrek',
    'shipments.weight': 'Gewicht',
    'shipments.value': 'Waarde',
    'shipments.created': 'Aangemaakt op',
    'shipments.tracking_number': 'Trackingnummer',
    'shipments.view_details': 'Details bekijken',
    'shipments.track': 'Volgen',
    'shipments.empty': 'Geen zendingen gevonden',
    'shipments.empty_subtitle': 'Begin met het aanmaken van je eerste zending',
    'shipments.total_results': '{count} zending(en) gevonden',
    
    // Shipment Form
    'shipment_form.title': 'Nieuwe Zending Aanmaken',
    'shipment_form.subtitle': 'Vul de informatie van je internationale zending in',
    'shipment_form.sender_info': 'Verzender Informatie',
    'shipment_form.recipient_info': 'Ontvanger Informatie',
    'shipment_form.package_info': 'Pakket Informatie',
    'shipment_form.customs_info': 'Douane Informatie',
    'shipment_form.sender_name': 'Naam verzender',
    'shipment_form.sender_company': 'Bedrijf verzender',
    'shipment_form.sender_address': 'Adres',
    'shipment_form.sender_city': 'Stad',
    'shipment_form.sender_postal': 'Postcode',
    'shipment_form.sender_country': 'Land',
    'shipment_form.sender_phone': 'Telefoon',
    'shipment_form.sender_email': 'Email',
    'shipment_form.recipient_name': 'Naam ontvanger',
    'shipment_form.recipient_company': 'Bedrijf ontvanger',
    'shipment_form.recipient_address': 'Adres',
    'shipment_form.recipient_city': 'Stad',
    'shipment_form.recipient_postal': 'Postcode',
    'shipment_form.recipient_country': 'Land',
    'shipment_form.recipient_phone': 'Telefoon',
    'shipment_form.recipient_email': 'Email',
    'shipment_form.package_type': 'Type pakket',
    'shipment_form.package_weight': 'Gewicht (kg)',
    'shipment_form.package_dimensions': 'Afmetingen (L x B x H in cm)',
    'shipment_form.package_value': 'Aangegeven waarde (€)',
    'shipment_form.package_description': 'Beschrijving inhoud',
    'shipment_form.package_quantity': 'Hoeveelheid',
    'shipment_form.customs_purpose': 'Doel van zending',
    'shipment_form.customs_hs_code': 'HS Code',
    'shipment_form.customs_origin': 'Land van oorsprong',
    'shipment_form.insurance': 'Verzekering',
    'shipment_form.insurance_value': 'Verzekerde waarde (€)',
    'shipment_form.delivery_options': 'Bezorgingsopties',
    'shipment_form.signature_required': 'Handtekening vereist',
    'shipment_form.express_delivery': 'Express bezorging',
    'shipment_form.calculate_cost': 'Kosten berekenen',
    'shipment_form.estimated_cost': 'Geschatte kosten',
    'shipment_form.create_shipment': 'Zending aanmaken',
    'shipment_form.save_draft': 'Concept opslaan',
    'shipment_form.required_field': 'Verplicht veld',
    'shipment_form.success': 'Zending succesvol aangemaakt',
    'shipment_form.error': 'Fout bij aanmaken zending',
    
    // Tracking
    'tracking.title': 'Zending Volgen',
    'tracking.subtitle': 'Volg je zending in realtime',
    'tracking.number': 'Trackingnummer',
    'tracking.status': 'Status',
    'tracking.location': 'Locatie',
    'tracking.estimated_delivery': 'Geschatte levering',
    'tracking.timeline': 'Tijdlijn',
    'tracking.details': 'Zending details',
    'tracking.share': 'Tracking delen',
    'tracking.download_label': 'Label downloaden',
    'tracking.contact_support': 'Contact ondersteuning',
    'tracking.not_found': 'Zending niet gevonden',
    'tracking.loading': 'Tracking laden...',
    'tracking.map_view': 'Kaartweergave',
    'tracking.list_view': 'Lijstweergave',
    
    // Customs
    'customs.title': 'Douane Assistent',
    'customs.subtitle': 'Beheer je douaneaangiftes met AI',
    'customs.generate_dau': 'DAU genereren',
    'customs.dau_number': 'DAU nummer',
    'customs.dau_status': 'DAU status',
    'customs.customs_value': 'Douanewaarde',
    'customs.duty_tax': 'Rechten en belastingen',
    'customs.documents': 'Documenten',
    'customs.requirements': 'Douane vereisten',
    'customs.country_regulations': 'Landregelgeving',
    'customs.prohibited_items': 'Verboden artikelen',
    'customs.restricted_items': 'Beperkte artikelen',
    'customs.ai_suggestions': 'AI suggesties',
    'customs.validate_declaration': 'Aangifte valideren',
    'customs.submit_declaration': 'Aangifte indienen',
    'customs.declaration_approved': 'Aangifte goedgekeurd',
    'customs.declaration_pending': 'Aangifte in behandeling',
    'customs.declaration_rejected': 'Aangifte afgewezen',
    
    // Consolidation
    'consolidation.title': 'Consolidatie Centrum',
    'consolidation.subtitle': 'Optimaliseer je zendingen met micro-consolidatie',
    'consolidation.available_groups': 'Beschikbare groepen',
    'consolidation.my_shipments': 'Mijn wachtende zendingen',
    'consolidation.join_group': 'Groep deelnemen',
    'consolidation.create_group': 'Groep maken',
    'consolidation.group_savings': 'Groepsbesparingen',
    'consolidation.departure_date': 'Vertrekdatum',
    'consolidation.capacity': 'Capaciteit',
    'consolidation.participants': 'Deelnemers',
    'consolidation.estimated_savings': 'Geschatte besparingen',
    'consolidation.total_weight': 'Totaalgewicht',
    'consolidation.total_volume': 'Totaalvolume',
    'consolidation.optimization_score': 'Optimalisatiescore',
    
    // Notifications
    'notifications.title': 'Meldingencentrum',
    'notifications.mark_all_read': 'Alles markeren als gelezen',
    'notifications.filter_all': 'Alle',
    'notifications.filter_unread': 'Ongelezen',
    'notifications.filter_shipments': 'Zendingen',
    'notifications.filter_customs': 'Douane',
    'notifications.filter_system': 'Systeem',
    'notifications.empty': 'Geen meldingen',
    'notifications.shipment_update': 'Zending update',
    'notifications.customs_alert': 'Douane alert',
    'notifications.system_update': 'Systeem update',
    'notifications.delivery_notification': 'Leveringsmelding',
    
    // Reports
    'reports.title': 'Rapporten en Analyses',
    'reports.subtitle': 'Analyseer je logistieke prestaties',
    'reports.period': 'Periode',
    'reports.last_7_days': 'Laatste 7 dagen',
    'reports.last_30_days': 'Laatste 30 dagen',
    'reports.last_90_days': 'Laatste 90 dagen',
    'reports.this_year': 'Dit jaar',
    'reports.custom_period': 'Aangepaste periode',
    'reports.total_shipments': 'Totaal zendingen',
    'reports.total_savings': 'Totale besparingen',
    'reports.average_cost': 'Gemiddelde kosten',
    'reports.delivery_performance': 'Leveringsprestaties',
    'reports.popular_destinations': 'Populaire bestemmingen',
    'reports.customs_efficiency': 'Douane efficiëntie',
    'reports.export_report': 'Rapport exporteren',
    'reports.generate_report': 'Rapport genereren',
    
    // Settings
    'settings.title': 'Account Instellingen',
    'settings.profile': 'Profiel',
    'settings.company': 'Bedrijf',
    'settings.preferences': 'Voorkeuren',
    'settings.notifications': 'Meldingen',
    'settings.security': 'Beveiliging',
    'settings.billing': 'Facturering',
    'settings.api': 'API',
    'settings.save_changes': 'Wijzigingen opslaan',
    'settings.changes_saved': 'Wijzigingen opgeslagen',
    'settings.language_preference': 'Taalvoorkeur',
    'settings.timezone': 'Tijdzone',
    'settings.currency': 'Valuta',
    'settings.email_notifications': 'Email meldingen',
    'settings.sms_notifications': 'SMS meldingen',
    'settings.push_notifications': 'Push meldingen',
    
    // Messages
    'messages.title': 'Berichten',
    'messages.compose': 'Nieuw bericht',
    'messages.inbox': 'Inbox',
    'messages.sent': 'Verzonden',
    'messages.drafts': 'Concepten',
    'messages.archive': 'Archief',
    'messages.subject': 'Onderwerp',
    'messages.message': 'Bericht',
    'messages.send': 'Verzenden',
    'messages.reply': 'Beantwoorden',
    'messages.forward': 'Doorsturen',
    'messages.delete': 'Verwijderen',
    'messages.mark_read': 'Markeren als gelezen',
    'messages.mark_unread': 'Markeren als ongelezen',
    'messages.empty': 'Geen berichten',
    
    // Help & Support
    'help.title': 'hubdispo.be Helpcentrum',
    'help.search_placeholder': 'Zoek in help...',
    'help.popular_topics': 'Populaire onderwerpen',
    'help.getting_started': 'Aan de slag',
    'help.shipping_guide': 'Verzendgids',
    'help.customs_help': 'Douane hulp',
    'help.troubleshooting': 'Probleemoplossing',
    'help.contact_support': 'Contact ondersteuning',
    'help.live_chat': 'Live chat',
    'help.phone_support': 'Telefoonondersteuning',
    'help.email_support': 'Email ondersteuning',
    'help.video_tutorials': 'Video tutorials',
    'help.documentation': 'Documentatie',
    'help.api_docs': 'API documentatie',
    
    // Subscription
    'subscription.title': 'Mijn Abonnement',
    'subscription.current_plan': 'Huidig plan',
    'subscription.upgrade': 'Upgraden',
    'subscription.downgrade': 'Downgraden',
    'subscription.cancel': 'Abonnement opzeggen',
    'subscription.billing_history': 'Facturatiehistorie',
    'subscription.next_billing': 'Volgende facturatie',
    'subscription.usage': 'Gebruik',
    'subscription.limits': 'Limieten',
    'subscription.features': 'Functies',
    'subscription.change_plan': 'Plan wijzigen',
    
    // Map
    'map.title': 'Routekaart',
    'map.shipments_on_map': 'Zendingen op kaart',
    'map.filter_by_status': 'Filteren op status',
    'map.route_optimization': 'Route optimalisatie',
    'map.live_tracking': 'Live tracking',
    'map.estimated_delivery': 'Geschatte levering',
    'map.view_details': 'Details bekijken',
    'map.consolidation_centers': 'Consolidatiecentra',
    
    // FAQ
    'faq.title': 'Veelgestelde Vragen',
    'faq.search_placeholder': 'Zoek in FAQ...',
    'faq.categories': 'Categorieën',
    'faq.general': 'Algemeen',
    'faq.shipping': 'Verzending',
    'faq.customs': 'Douane',
    'faq.billing': 'Facturering',
    'faq.technical': 'Technisch',
    'faq.helpful': 'Was dit antwoord behulpzaam?',
    'faq.yes': 'Ja',
    'faq.no': 'Nee',
    'faq.contact_support': 'Contact ondersteuning',
    
    // Alerts
    'alerts.title': 'Intelligent Alertsysteem',
    'alerts.custom_alerts': 'Aangepaste alerts',
    'alerts.delivery_alerts': 'Leveringsalerts',
    'alerts.customs_alerts': 'Douane alerts',
    'alerts.price_alerts': 'Prijsalerts',
    'alerts.create_alert': 'Alert maken',
    'alerts.manage_alerts': 'Alerts beheren',
    'alerts.alert_triggered': 'Alert geactiveerd',
    'alerts.alert_resolved': 'Alert opgelost',
    
    // Status Messages
    'status.loading': 'Laden...',
    'status.saving': 'Opslaan...',
    'status.saved': 'Opgeslagen',
    'status.error': 'Fout',
    'status.success': 'Succesvol',
    'status.warning': 'Waarschuwing',
    'status.info': 'Informatie',
    'status.connecting': 'Verbinden...',
    'status.connected': 'Verbonden',
    'status.disconnected': 'Verbinding verbroken',
    
    // Actions
    'actions.save': 'Opslaan',
    'actions.cancel': 'Annuleren',
    'actions.delete': 'Verwijderen',
    'actions.edit': 'Bewerken',
    'actions.view': 'Bekijken',
    'actions.download': 'Downloaden',
    'actions.upload': 'Uploaden',
    'actions.share': 'Delen',
    'actions.copy': 'Kopiëren',
    'actions.print': 'Afdrukken',
    'actions.export': 'Exporteren',
    'actions.import': 'Importeren',
    'actions.search': 'Zoeken',
    'actions.filter': 'Filteren',
    'actions.sort': 'Sorteren',
    'actions.refresh': 'Verversen',
    'actions.close': 'Sluiten',
    'actions.back': 'Terug',
    'actions.next': 'Volgende',
    'actions.previous': 'Vorige',
    'actions.continue': 'Doorgaan',
    'actions.confirm': 'Bevestigen',
    'actions.submit': 'Indienen',
    'actions.send': 'Verzenden',
    'actions.retry': 'Opnieuw proberen',
    'actions.undo': 'Ongedaan maken',
    'actions.redo': 'Opnieuw doen'
  }
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>('fr');

  // Load language from localStorage on mount
  useEffect(() => {
    try {
      const savedLanguage = localStorage.getItem('hubdispo-language') as Language;
      if (savedLanguage && ['fr', 'en', 'nl'].includes(savedLanguage)) {
        setLanguageState(savedLanguage);
      } else {
        // Detect browser language
        const browserLang = navigator.language.toLowerCase();
        if (browserLang.startsWith('nl')) {
          setLanguageState('nl');
        } else if (browserLang.startsWith('en')) {
          setLanguageState('en');
        } else {
          setLanguageState('fr');
        }
      }
    } catch (error) {
      console.warn('Error loading language from localStorage:', error);
      setLanguageState('fr');
    }
  }, []);

  // Save language to localStorage when changed
  const setLanguage = (lang: Language) => {
    try {
      setLanguageState(lang);
      localStorage.setItem('hubdispo-language', lang);
      console.log('Language changed to:', lang); // Debug log
    } catch (error) {
      console.warn('Error saving language to localStorage:', error);
      setLanguageState(lang);
    }
  };

  // Translation function with parameter replacement
  const t = (key: string, params?: Record<string, string>) => {
    try {
      const langTranslations = translations[language];
      if (!langTranslations) {
        console.warn(`No translations found for language: ${language}`);
        return key;
      }
      
      const translation = langTranslations[key as keyof typeof translations['fr']] || key;
      
      if (params) {
        return Object.entries(params).reduce((acc, [paramKey, paramValue]) => {
          return acc.replace(new RegExp(`{${paramKey}}`, 'g'), paramValue);
        }, translation);
      }
      
      return translation;
    } catch (error) {
      console.warn('Error in translation function:', error);
      return key;
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}